name: 'build tar'
description: 'Build and install tar'
inputs:
  version:
    description: 'tar version'
    required: false
    default: '1.35'
  prefix:
    description: 'configure prefix'
    required: false
    default: '/usr'
  container-name:
    description: 'name of container used to build in'
    required: false
    default: ''
runs:
  using: composite
  steps:
    - name: build tar (runner)
      if: ${{ inputs.container-name == '' }}
      env:
        VERSION: ${{ inputs.version }}
        PREFIX: ${{ inputs.prefix }}
      run: ${{ github.action_path }}/build.sh
      shell: bash

    - name: build tar (container)
      if: ${{ inputs.container-name != '' }}
      run: |
        docker container cp ${{ github.action_path }}/build.sh ${{ inputs.container-name }}:/workspace/tar-build.sh
        docker exec -e VERSION=${{ inputs.version }} -e PREFIX=${{ inputs.prefix }} -w /workspace ${{ inputs.container-name }} bash -l tar-build.sh
      shell: bash
