name: 'build btfhub'
description: 'Build and install btfhub'
inputs:
  go-path:
    description: 'path to go'
    required: false
    default: 'go'
  container-name:
    description: 'name of container used to build in'
    required: false
    default: ''
runs:
  using: composite
  steps:
    - name: build btfhub (runner)
      if: ${{ inputs.container-name == '' }}
      env:
        CMD_GO: ${{ inputs.go-path }}
      run: make
      shell: bash

    - name: build btfhub (container)
      if: ${{ inputs.container-name != '' }}
      run: docker exec -e CMD_GO=${{ inputs.go-path }} -w /workspace ${{ inputs.container-name }} bash -l -c "make"
      shell: bash
