---
include:
  - .gitlab/common.yml
  - .gitlab/btf.yml
  - .gitlab/image.yml
  - .gitlab/rhel.yml
  - .gitlab/pr.yml
  - .gitlab/catalog.yml

variables:
  CI_IMAGE_REPO: "ci/${CI_PROJECT_NAME}"
  IMAGE_VERSION: "v66563033-382d76f1"
  SUB_IMAGE_VERSION: "v59502123-970bf756"
  VAULT_VERSION: "1.17.2"
  VAULT_SHA256_LINUX_AMD64: a0c0449e640c8be5dcf7b7b093d5884f6a85406dbb86bbad0ea06becad5aaab8
  FF_TIMESTAMPS: "true"
  FF_SCRIPT_SECTIONS: "true"

stages:
  - setup
  - test
  - build_image
  - btf
  - catalog
  - cleanup

default:
  retry:
    max: 1
    when:
      - unknown_failure
      - data_integrity_failure
      - runner_system_failure
      - scheduler_failure
      - api_failure

.if_scheduled_main: &if_scheduled_main
  if: $CI_PIPELINE_SOURCE == "schedule" && $CI_COMMIT_BRANCH == "main"

.on_image_changes:
  - changes:
      paths:
        - ci-images/**
        - .gitlab/image.yml
        - .gitlab/rhel.yml
      compare_to: main

.on_btf_changes:
  - changes:
      paths:
        - .gitlab/btf.yml

.on_scheduled_main:
  - <<: *if_scheduled_main
    when: always

.manual:
  - when: manual
