version: "2"
linters:
  settings:
    errcheck:
      exclude-functions:
        - (*os.File).Close
        - (io.ReadCloser).Close
        - (*compress/gzip.Reader).Close
        - os.Remove
        - os.RemoveAll
