name: 'build pahole'
description: 'Build and install pahole'
inputs:
  container-name:
    description: 'name of container used to build in'
    required: false
    default: ''
runs:
  using: composite
  steps:
    - name: build pahole (runner)
      if: ${{ inputs.container-name == '' }}
      run: ${{ github.action_path }}/build.sh
      shell: bash

    - name: build pahole (container)
      if: ${{ inputs.container-name != '' }}
      run: |
        docker container cp ${{ github.action_path }}/build.sh ${{ inputs.container-name }}:/workspace/pahole-build.sh
        docker exec -w /workspace ${{ inputs.container-name }} bash -l pahole-build.sh
      shell: bash
