name: 'commit BTFs'
description: 'commit and push changed BTFs to btfhub-archive'
inputs:
  platform:
    description: 'btf platform'
    required: true
runs:
  using: composite
  steps:
    - name: commit and push to btfhub-archive
      run: |
        cd archive
        git status
        git config --local user.name "Bryce Kahle"
        git config --local user.email "bryce.kahle@datadoghq.com"
        git add -A
        git diff-index --quiet HEAD || git commit -m "${{ inputs.platform }} update on $(date -u +%Y-%m-%d)"
        git push || (git pull --rebase && git push)
      shell: bash
