name: Build Dependencies
description: |
  Install build dependencies to test and compile btfhub artifacts
runs:
  using: composite
  steps:
    - uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a
      with:
        go-version-file: 'go.mod'

    - name: Install ubuntu packages
      run: |
        export DEBIAN_FRONTEND=noninteractive
        sudo dpkg --purge unattended-upgrades
        sudo apt-get update
        sudo apt-get install -y bsdutils build-essential pkgconf
        sudo apt-get install -y zlib1g-dev libelf-dev
        sudo apt-get install -y software-properties-common
        sudo apt-get install -y devscripts ubuntu-dev-tools
      shell: bash

    - name: Install llvm
      run: |
        export DEBIAN_FRONTEND=noninteractive
        sudo apt-get install -y clang-14 clangd-14 clang-tools-14 clang-format-14
        sudo apt-get install -y llvm-14 llvm-14-runtime llvm-14-tools 
        sudo update-alternatives --remove-all cc || true
        sudo update-alternatives --remove-all clang || true
        sudo update-alternatives --remove-all clang++ || true
        sudo update-alternatives --remove-all llc || true
        sudo update-alternatives --remove-all lld || true
        sudo update-alternatives --remove-all clangd || true
        sudo update-alternatives --remove-all clang-format || true
        sudo update-alternatives --remove-all llvm-strip || true
        sudo update-alternatives --remove-all llvm-config || true
        sudo update-alternatives --remove-all ld.lld || true
        sudo update-alternatives --remove-all llvm-ar || true
        sudo update-alternatives --remove-all llvm-nm || true
        sudo update-alternatives --remove-all llvm-objcopy || true
        sudo update-alternatives --remove-all llvm-objdump || true
        sudo update-alternatives --remove-all llvm-readelf || true
        sudo update-alternatives --remove-all opt || true
        sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-14 140 \
          --slave /usr/bin/clang++ clang++ /usr/bin/clang++-14 \
          --slave /usr/bin/clangd clangd /usr/bin/clangd-14 \
          --slave /usr/bin/clang-format clang-format /usr/bin/clang-format-14 \
          --slave /usr/bin/lld lld /usr/bin/lld-14 \
          --slave /usr/bin/llc llc /usr/bin/llc-14 \
          --slave /usr/bin/llvm-strip llvm-strip /usr/bin/llvm-strip-14 \
          --slave /usr/bin/llvm-config llvm-config /usr/bin/llvm-config-14 \
          --slave /usr/bin/ld.lld ld.lld /usr/bin/ld.lld-14 \
          --slave /usr/bin/llvm-ar llvm-ar /usr/bin/llvm-ar-14 \
          --slave /usr/bin/llvm-nm llvm-nm /usr/bin/llvm-nm-14 \
          --slave /usr/bin/llvm-objcopy llvm-objcopy /usr/bin/llvm-objcopy-14 \
          --slave /usr/bin/llvm-objdump llvm-objdump /usr/bin/llvm-objdump-14 \
          --slave /usr/bin/llvm-readelf llvm-readelf /usr/bin/llvm-readelf-14 \
          --slave /usr/bin/opt opt /usr/bin/opt-14 \
          --slave /usr/bin/cc cc /usr/bin/clang-14
      shell: bash

    - name: Install staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@56172d41b117cc2c2f99f65fe0a790c8d7d7ea66
      shell: bash
