name: 'build elfutils'
description: 'Build and install elfutils'
inputs:
  version:
    description: 'elfutils version'
    required: false
    default: '0.190'
  container-name:
    description: 'name of container used to build in'
    required: false
    default: ''
runs:
  using: composite
  steps:
    - name: build elfutils (runner)
      if: ${{ inputs.container-name == '' }}
      env:
        VERSION: ${{ inputs.version }}
      run: ${{ github.action_path }}/build.sh
      shell: bash

    - name: build elfutils (container)
      if: ${{ inputs.container-name != '' }}
      run: |
        docker container cp ${{ github.action_path }}/build.sh ${{ inputs.container-name }}:/workspace/elfutils-build.sh
        docker exec -e VERSION=${{ inputs.version }} -w /workspace ${{ inputs.container-name }} bash -l elfutils-build.sh
      shell: bash
