name: direct package repo access update
on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch: {}
jobs:
  update-archive:
    strategy:
      fail-fast: false
      matrix:
        distro: [ ubuntu, debian, centos, fedora, ol, opensuse-leap ]
    name: ${{ matrix.distro }}
    runs-on: ubuntu-24.04
    steps:
      - name: free up some disk space
        run: |
          sudo rm -rf /usr/local/lib/android || true
          sudo rm -rf /usr/share/dotnet || true
          sudo rm -rf /opt/ghc || true
          sudo rm -rf /usr/local/.ghcup || true
          sudo docker image prune --all --force || true
          sudo apt-get remove -y --fix-missing '^aspnetcore-.*' '^dotnet-.*' 'php.*' '^mongodb-.*' '^mysql-.*' azure-cli google-chrome-stable firefox powershell mono-devel libgl1-mesa-dri google-cloud-sdk google-cloud-cli || true

      - name: install required packages
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo dpkg --purge unattended-upgrades
          sudo apt-get update
          sudo apt-get install -y bsdutils build-essential pkgconf zlib1g-dev libdw-dev libdwarf-dev libelf-dev software-properties-common devscripts ubuntu-dev-tools clang llvm
          sudo apt-get autoremove -y || true
          sudo apt-get clean || true

      - name: authenticate
        run: |
          gh auth login --with-token <<<'${{ secrets.DD_BTFHUB_BOT_GITHUB_TOKEN }}'

      - name: checkout btfhub
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          token: ${{ secrets.DD_BTFHUB_BOT_GITHUB_TOKEN }}
          submodules: 'recursive'

      - name: checkout btfhub-archive
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          repository: DataDog/btfhub-archive
          ref: main
          token: ${{ secrets.DD_BTFHUB_BOT_GITHUB_TOKEN }}
          path: archive
          sparse-checkout: |
            ${{ matrix.distro }}

      - uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a
        with:
          go-version-file: 'go.mod'

      - name: build pahole
        uses: ./.github/actions/build-pahole

      - name: build bpftool
        uses: ./.github/actions/build-bpftool

      - name: build btfhub
        uses: ./.github/actions/build-btfhub

      - name: generate BTFs
        run: |
          ./btfhub -workers 6 -d ${{ matrix.distro }}

      - name: commit and push to btfhub-archive
        uses: ./.github/actions/commit-btfs
        with:
          platform: "update ${{ matrix.distro }}"
