name: Update BTFHub Archive
on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch: {}
jobs:
  update-archive:
    strategy:
      matrix:
        distro: [ ubuntu, debian, centos, fedora, ol, opensuse-leap ]
    name: update btfhub-archive
    runs-on: ubuntu-latest
    steps:
    #
      - name: Install needed ubuntu packages
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo dpkg --purge unattended-upgrades
          sudo apt-get update
          sudo apt-get install -y clang bsdutils build-essential pkgconf zlib1g-dev libdw-dev libdwarf-dev libelf-dev software-properties-common devscripts ubuntu-dev-tools
        shell: bash
    #
      - name: Authenticate
        run: |
          gh auth login --with-token <<<'${{ secrets.DD_BTFHUB_BOT_GITHUB_TOKEN }}'
    #
      - name: Check out BTFHub
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.DD_BTFHUB_BOT_GITHUB_TOKEN }}
          submodules: 'recursive'

      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
    #
      - name: build pahole
        run: |
          cd ./3rdparty/dwarves
          mkdir build
          cd build
          cmake -D__LIB=lib ..
          sudo make install
          echo "/usr/local/lib" | sudo tee /etc/ld.so.conf.d/pahole.conf
          sudo ldconfig
        shell: bash
    #
      - name: Compile BTFHub Tool
        run: make
        shell: bash
    #
      - name: Checkout BTFHub Archive
        uses: actions/checkout@v3
        with:
          repository: DataDog/btfhub-archive
          token: ${{ secrets.DD_BTFHUB_BOT_GITHUB_TOKEN }}
          path: archive
          sparse-checkout: |
            ${{ matrix.distro }}
    #
      - name: Setup git config
        run: |
          cd archive
          git config --local user.name "Bryce Kahle"
          git config --local user.email "bryce.kahle@datadoghq.com"
    #
      - name: Fetch and Generate new BTFs
        run: |
          ./btfhub -workers 6 -d ${{ matrix.distro }}
    #
      - name: Check Status
        run: |
          cd archive
          git status
    #
      - name: Commit and Push to BTFHub Archive
        run: |
          cd archive
          git add -A
          git diff-index --quiet HEAD || git commit -m "update ${{ matrix.distro }} btfhub-archive on $(date -u +%Y-%m-%d)"
          git push || (git pull --rebase && git push)
