name: PR
on:
  workflow_dispatch: {}
  pull_request:
    branches:
      - main
    paths:
      - "!docs/**"
      - "!archive/**"
      - "!custom-archive/**"
      - "!tools/bin/**"
      - "!**.yaml"
      - "!**.md"
      - "!**.txt"
      - "!**.conf"
      # override previous rules:
      - "**.c"
      - "**.h"
      - "**.go"
      - "**.sh"
      - ".github/workflows/pr.yaml"
concurrency:
  group: ${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
jobs:
  #
  # CODE VERIFICATION
  #
  verify-analyze-code:
    name: Verify and Analyze Code
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install Dependencies
        uses: ./.github/actions/build-dependencies

      - name: Lint
        run: |
          if test -z "$(gofmt -l .)"; then
            echo "Congrats! There is nothing to fix."
          else
            echo "The following lines should be fixed."
            gofmt -s -d .
            exit 1
          fi

      - name: Check Golang Vet
        run: |
          make check-vet

      - name: Check with StaticCheck
        run: |
          make check-staticcheck
  #
  # CODE TESTS
  #
  unit-tests:
    name: Unit Tests
    needs:
      - verify-analyze-code
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install Dependencies
        uses: ./.github/actions/build-dependencies

      - name: Run Unit Tests
        run: |
          make test-unit
