name: RHEL 8
on:
  push:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch: {}
env:
  BTFHUB_NO_SUDO: true
jobs:
  rhel8-update:
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        platform: [ "linux/amd64", "linux/arm64" ]
        include:
          - platform: "linux/amd64"
            arch: "x86_64"
            alt_arch: "x86_64"
          - platform: "linux/arm64"
            arch: "arm64"
            alt_arch: "aarch64"
    name: rhel 8 ${{ matrix.arch }}
    runs-on: ubuntu-latest
    container:
      image: registry.access.redhat.com/ubi8/ubi:latest
      options: --platform ${{ matrix.platform }}
    steps:
      - name: setup subscription
        run: |
          rm -rf /etc/rhsm-host
          subscription-manager register --org=${{ secrets.DD_BTFHUB_RHEL_ORG_ID }} --activationkey="btfhub-ci"
          subscription-manager repos --enable=rhel-8-for-${{ matrix.alt_arch }}-baseos-debug-rpms

      - name: install required packages
        run: |
          yum-config-manager --add-repo https://cli.github.com/packages/rpm/gh-cli.repo
          yum install -y yum-utils wget bzip2 zlib-devel m4 xz gzip cmake make clang-12.0.1 gcc gh

      - name: github authenticate
        run: |
          gh auth login --with-token <<<'${{ secrets.DD_BTFHUB_BOT_GITHUB_TOKEN }}'

      - name: checkout btfhub
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.DD_BTFHUB_BOT_GITHUB_TOKEN }}
          submodules: 'recursive'

      - run: git config --system --add safe.directory $(pwd)

      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: build elfutils
        run: |
          wget -nv https://sourceware.org/elfutils/ftp/0.190/elfutils-0.190.tar.bz2
          tar xf elfutils-0.190.tar.bz2
          cd elfutils-0.190
          ./configure --disable-libdebuginfod --disable-debuginfod --disable-demangler
          make install
          ldconfig

      - name: build tar
        run: |
          wget -nv https://ftpmirror.gnu.org/tar/tar-1.35.tar.xz
          tar xf tar-1.35.tar.xz
          cd tar-1.35
          FORCE_UNSAFE_CONFIGURE=1 ./configure --prefix=/usr
          make install            

      - name: build pahole
        run: |
          cd ./3rdparty/dwarves
          mkdir build
          cd build
          cmake -D__LIB=lib -DDWARF_INCLUDE_DIR=/usr/include ..
          make install
          echo "/usr/local/lib" >> /etc/ld.so.conf.d/pahole.conf
          ldconfig

      - name: build btfhub
        run: |
          make

      - name: checkout btfhub-archive
        uses: actions/checkout@v3
        with:
          repository: DataDog/btfhub-archive
          token: ${{ secrets.DD_BTFHUB_BOT_GITHUB_TOKEN }}
          path: archive
          sparse-checkout: |
            rhel/8/${{ matrix.arch }}

      - name: generate BTFs
        run: |
          ./btfhub -workers 6 -d rhel -r 8 -a ${{ matrix.arch }}

      - name: check status
        run: |
          cd archive
          git status

      - name: commit and push to btfhub-archive
        run: |
          cd archive
          git config --local user.name "Bryce Kahle"
          git config --local user.email "bryce.kahle@datadoghq.com"
          git add -A
          git diff-index --quiet HEAD || git commit -m "rhel 8 ${{ matrix.arch }} update on $(date -u +%Y-%m-%d)"
          git push || (git pull --rebase && git push)

      - name: unregister from RHEL
        if: always()
        run: |
          subscription-manager remove --all
          subscription-manager unregister
          subscription-manager clean
